// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFyxKQCWUR98YaRbVuS3h36rpfvga-Xc0',
    appId: '1:95060390664:web:3d15a75d311eb7f7a7b2bd',
    messagingSenderId: '95060390664',
    projectId: 'vivasync-61b5b',
    authDomain: 'vivasync-61b5b.firebaseapp.com',
    storageBucket: 'vivasync-61b5b.firebasestorage.app',
    measurementId: 'G-MMYL73FFQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDELq4aaidQhWbXpnGi-YgPvonFFbbt0Bw',
    appId: '1:95060390664:android:086f03b900925bdca7b2bd',
    messagingSenderId: '95060390664',
    projectId: 'vivasync-61b5b',
    storageBucket: 'vivasync-61b5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHcxDjrH4J_lLLqZYgEb4sK9uX2p4Oxfo',
    appId: '1:95060390664:ios:c29b93cfcbe6d238a7b2bd',
    messagingSenderId: '95060390664',
    projectId: 'vivasync-61b5b',
    storageBucket: 'vivasync-61b5b.firebasestorage.app',
    iosBundleId: 'com.example.vivasync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHcxDjrH4J_lLLqZYgEb4sK9uX2p4Oxfo',
    appId: '1:95060390664:ios:c29b93cfcbe6d238a7b2bd',
    messagingSenderId: '95060390664',
    projectId: 'vivasync-61b5b',
    storageBucket: 'vivasync-61b5b.firebasestorage.app',
    iosBundleId: 'com.example.vivasync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFyxKQCWUR98YaRbVuS3h36rpfvga-Xc0',
    appId: '1:95060390664:web:84b56cbe67b223aaa7b2bd',
    messagingSenderId: '95060390664',
    projectId: 'vivasync-61b5b',
    authDomain: 'vivasync-61b5b.firebaseapp.com',
    storageBucket: 'vivasync-61b5b.firebasestorage.app',
    measurementId: 'G-8NQFFYCHJE',
  );
}
